### ISSUE TITLE
Unable to connect if server was started twice on different ports

### ISSUE THREAD

**Issue by azzamsa** [40ants/weblocks#12]
I tried to follow the quickstart. But I can't connect to weblock server.

I tried to explicitly defined the port. But it doesn't works.

``` cl
(weblocks/server:start :port 8000)
 <INFO> [16:39:50] weblocks/server server.lisp (start) -
  Starting weblocks WEBLOCKS/SERVER::PORT: 8000
  WEBLOCKS/SERVER::SERVER-TYPE: :HUNCHENTOOT DEBUG: T 
NIL
TODO> 
```

``` bash
user at machine in ~/common-lisp
$ curl http://localhost:8000/
curl: (7) Failed to connect to localhost port 8000: Connection refused

user at machine in ~/common-lisp
$ curl http://localhost:8000/task
curl: (7) Failed to connect to localhost port 8000: Connection refused
```

**Comment by svetlyak40wt** [comment]
Please, provide an output of the command `netstat -nlpt`, executed when the server is running.

**Comment by azzamsa** [comment]
I've succeeded to produce the error.

It was caused by changing weblock port on the fly without shutting it down.

I get port 40000 from *port* by using `(defvar *port*
(find-port:find-port))`. I want to change it since it's wierd for me
to have development web app on port 40000.

I changed it using 

``` cl
(weblocks/server:start :port 4000)
```

The sad thing is: There is no error massage for doing this *wrong*
thing. Instead I get sucess like massage.

``` cl
(weblocks/server:start :port 8000)
 <INFO> [16:39:50] weblocks/server server.lisp (start) -
  Starting weblocks WEBLOCKS/SERVER::PORT: 8000
  WEBLOCKS/SERVER::SERVER-TYPE: :HUNCHENTOOT DEBUG: T 
NIL
TODO> 
```

But when I tried to access localhost:8000. firefox says "unable to
connect".

It solved by shutting down weblock. then start with new specified port

``` cl
(weblocks/server:stop)
```

``` cl
(weblocks/server:start :port 8000)
```

Thanks for Reblocks :)
Happy Hacking.

**Comment by svetlyak40wt** [comment]
@azzamsa I this issue should be fixed anyway, to make Weblocks more user-friendly.

By the way, did you manage to go through the quickstart guide?

**Comment by azzamsa** [comment]
>  I this issue should be fixed anyway, to make Weblocks more user-friendly.

Yes. I think there should be a : 

1) if we don't want to change core functionality. I think We have to warn that weblock still using other port.
2) else. we can kill unused port and change the port on the fly (without shutting it down)

I closed the issue. Because I thought the problem caused by web server that weblock is using. or it was the core functionality that will take lot of amount of work to change. :)

I just tried to load my old caveman app. This is what happened when I tried to change port on the fly.

```cl
(dokterkucing:start :port 8080)
```

``` cl
Server is already running.
   [Condition of type SIMPLE-ERROR]

Restarts:
 0: [RESTART-SERVER] Restart the server
 1: [RETRY] Retry SLIME REPL evaluation request.
 2: [*ABORT] Return to SLIME's top level.
 3: [ABORT] abort thread (#<THREAD "repl-thread" RUNNING {1003077FA3}>)

Backtrace:
  0: (SB-KERNEL:WITH-SIMPLE-CONDITION-RESTARTS ERROR NIL "Server is already running.")
  1: (DOKTERKUCING:START :PORT 8080)
  2: (SB-INT:SIMPLE-EVAL-IN-LEXENV (DOKTERKUCING:START :PORT 8080) #<NULL-LEXENV>)
  3: (EVAL (DOKTERKUCING:START :PORT 8080))
 --more--
```

> By the way, did you manage to go through the quickstart guide?

To be honest. I really want to try weblock this week. But, tomorrow I have an agenda. So I will try to finish the quickstart at weekend.

I saw weblock use something like cl-who to make a front-end. I think I love to go with Djula. Building HTML with cl systax is hard for me. :)

---
Sorry. But somepeople call this project reblock, someother reblock. what is the right one ?

**Comment by svetlyak40wt** [comment]
I've closed this issue in commit https://github.com/40ants/weblocks/commit/4e9e5b9f43a4c7e5bedcccebdb4b7a3aa0177326

**Comment by svetlyak40wt** [comment]
The proper name of the project is Weblocks. I've talked with the current maintainer of the Weblocks and he is not going to maintain the project anymore and agreed to handle it to me.

However, code in `reblocks` branch highly incompatible with old Weblocks version and API will likely be changed in the future. That is why I don't hurry to push it to the quicklisp.

Probably I'll setup a separate quicklisp distribution for Weblocks and related projects to make it easier to be on the edge.

**Comment by azzamsa** [comment]
> I've closed this issue in commit 4e95b9

It's particularly fast to make changes in lisp program :)

> The proper name of the project is Weblocks. I've talked with the current maintainer of the Weblocks and he is not going to maintain the project anymore and agreed to handle it to me.

Wow. thank you for your time. 

> However, code in reblocks branch highly incompatible with old Weblocks version and API will likely be changed in the future. That is why I don't hurry to push it to the quicklisp.

Is that mean we will have two separate project ? weblock & reblock ? or weblock will be renamed to reblock ?

**Comment by azzamsa** [comment]
Sorry for this question.

I don't have big experience in building web apps. I saw many person put lot of promises in this project.

What I don't understand is: 1) what is the differences between weblock with usual web framework e.g caveman, nigle ? . what make weblock special ?

**Comment by svetlyak40wt** [comment]
> Is that mean we will have two separate project ? weblock & reblock ? or weblock will be renamed to reblock?

This mean that eventually (probably somewhere at the end of 2018) "reblocks" branch will become the main branch. No fixes will be made to the original Weblocks and all new features will appear only in newer Weblocks. By the way "reblocks" name for the branch, was born as conjunction of two words "refactored" and "weblocks" – "reblocks". But this is not a name of the project, this is just a branch name.

About the difference
---------------------

With most other web frameworks you are creating a bunch of functions which render HTML (or JSON) in response to particular URLs.

Weblocks is different because it operates a term "application" what you are building is an application consisting of widgets. An application is stateful and all business logic can be implemented in pure Common Lisp on the server-side, without a line of Javascript. For a user, this application will appear as a modern single-page application because its state will be made without page reloading. For a developer perspective, application consists from widgets, methods responsible for widget rendering and functions responsible for the processing of user's actions.

**Comment by azzamsa** [comment]
> This mean that eventually (probably somewhere at the end of 2018) "reblocks" branch will become the main branch

That will be great :)

> About the difference

After reading your explanation. I seems lost. I know weblock year ago. I read [this article](https://web.archive.org/web/20160314075734/http://www.defmacro.org/ramblings/continuations-web.html) but I don't get it. So I came back to my REPL to learn CL (that the early week I learn CL).

Many questions pops up in my mind. "widget in web app", is that like programming desktop App?, We can do many beautiful things with JS, is that "without line of js" really can provide similar result?,. HTML do action with js, how can we develop web app without js?.

With bunch of question. I try to inspect asd files. I suspect that it will use JSCL/parenscript. But turn out that parenscript commented. I tried to read "continuations-based web framework". But I still don't get it. Maybe I need more time in weekend.

By the way. thank you for explanation. Without jumping into technical things. Your explanation is really enough. "Building web app with widget".

---

The last paragraph of [this comments](https://www.reddit.com/r/lisp/comments/8jzpzw/why_did_you_decide_to_learn_lisp/dz4l0z8/) that drag me here. 

The old page of weblock contain some nice info and screenshot.

>What is Weblocks?
Weblocks is a continuations-based web framework written in Common Lisp.

I hope we can expand [wikipedia page](https://en.wikipedia.org/wiki/Weblocks) of weblock.

**Comment by vindarel** [comment]
Hello,

you don't need to understand the continuations now, Weblocks doesn't use them by default. The quickstart doesn't use them.

> is that like programming desktop App?

I read continuations allow this.

> how can we develop web app without js?.

Weblocks does ajax calls (so, with JS) for us, and updates the DOM (with JS) for us.

I agree that's puzzling, we must try to believe it ;)

**Comment by vindarel** [comment]
> But it turns out that parenscript is commented

True in weblocks.asd, but `rgrep` shows it is included in `src/package.lisp` and used in for exple `js/base.lisp` (`ps:…`).

**Comment by svetlyak40wt** [comment]
Continuations was excluded from the core, but I hope to return their support as a separate system `weblocks-cont`. I've talked to the previous maintainer of the Weblocks and he told that his predecessor intended to remove continuations because they made code of the framework more complex.

**Comment by svetlyak40wt** [comment]
> True in weblocks.asd, but rgrep shows it is included in src/package.lisp and used in for exple js/base.lisp (ps:…).

With :package-inferred asdf system you don't have to specify all dependencies in asd file.

**Comment by svetlyak40wt** [comment]
By the way, @azzamsa, I've created a Gitter chat about weblocks. You can ask your questions there. https://gitter.im/40ants/weblocks
