### ISSUE TITLE
Document tables and get-html-tag

### ISSUE THREAD

**Issue by vindarel** [40ants/weblocks#18]
When rendering widgets in tables, we can have a surprise of a badly rendered page. This is due to the fact of Weblocks surrounding its Widget html with a `div` which gets a proper id. But for tables, we don't want a `div`. The `get-html-tag` method of our widget must return `:tr`. Document this.

(I self-assign this.)

**Comment by svetlyak40wt** [comment]
I think that may be we need to eliminate this issue completely and automatically change widget's html tag from `:div` to `tr` if it is rendered right inside the `:table` tag, and to `:td` if it is rendered right inside the `:tr` tag.

We need to investigate if it is possible to understand the context and which tag is "outer" with `spinneret`. Something like that should be possible:

```lisp
(let (outer)
    (with-html
        (:table
            (setf outer
                     (get-outer-tag))))
     outer)

-> :TABLE
```

**Comment by svetlyak40wt** [comment]
Bu the way, @vindarel, do you want to join a 40Ant's "agile" dashboard at ZenHub, I've recently created?

**Comment by vindarel** [comment]
\+ 1

yes, I did accept the invitation yesterday. It seems I have a read-only permission and thus I can't move teh cards around.

**Comment by vindarel** [comment]
this seems exactly what we need: https://github.com/ruricolist/spinneret/#get-html-path

    (get-html-path) ;-> '(:table :section :body :html)

the example is even about tables.

**Comment by svetlyak40wt** [comment]
Great!

**Comment by svetlyak40wt** [comment]
> yes, I did accept the invitation yesterday
Interesting. I don't see you among team members, but see the invite I've sent 4 days ago.

I resent invite link right now. Try again please.
