### ISSUE TITLE
Is it possible to use a websocket from the client side?

### ISSUE THREAD

**Issue by ralt** [40ants/weblocks#39]
I'm not sure what the API would look like, and I did see https://github.com/40ants/weblocks-websocket, but it only has support for events sent from the server.

I'd like to have bidirectional support, i.e. I want to send things from the browser side. I assume I'd have to use `(make-js-action)`, but I need a way to abstract the JS I guess?

Sorry, I guess I'm looking for hints of how to implement that rather than an actual solution, which looks like it doesn't exist yet. I'd love to be proven wrong though!

**Comment by ralt** [comment]
A simple use case for that would be a chat.

**Comment by svetlyak40wt** [comment]
Yes, there is no support for interaction from the client side.

To experiment with this, you need to extend this part of JS code: https://github.com/40ants/weblocks-websocket/blob/master/src/websocket.lisp#L130-L146 to store websocket object globally, like in the `window.weblocks_websocket`.

After that, you will need to modify this ``on-message`` definition:

https://github.com/40ants/weblocks-websocket/blob/master/src/websocket.lisp#L29-L35

For example, it could find a widget somehow and call a method `on-message` on this widget. But we need to introduce a registry of all widgets, inherited from the `weblocks-widget`.

As you can see, this doable, but not implemented yet. I have no time now to experiment, but would like to know about your results. Feel free to send a pull requests into the https://github.com/40ants/weblocks-websocket !
