### ISSUE TITLE
Default value "localhost" to wookie of function weblocks/server:start is invalid 

### ISSUE THREAD

**Issue by not-null-nil** [40ants/weblocks#58]
when call something likes `(weblocks/server:start :port 40000 :server-type :wookie)`
It gives:`Invalid address passed (not IPv4 or IPV6): "localhost"`
Although localhost can be specified manually, I think it is not a bad idea to change the default value.

**Comment by svetlyak40wt** [comment]
Which default value for `interface` do you suggest instead of `"localhost"`?

**Comment by not-null-nil** [comment]
Maybe something like `"127.0.0.1"`? I saw clack use it [as default](https://github.com/fukamachi/clack/blob/e104b327d9eab3ce26ce1d809f8f5e0efe79864e/src/clack.lisp#L73).

**Comment by svetlyak40wt** [comment]
`"127.0.0.1"` is a bad choice, because there are IPv6 only servers in the world, where it will not work. "localhost" resolves into the correct IP address. If some backend is not doing this resolve, then we need to do this in the Weblocks. Like this:

```
CL-USER> (usocket:get-host-by-name "localhost")
#(127 0 0 1)
```

But most probably the better place to do this is Clack, because it is our glue for all backends.

**Comment by not-null-nil** [comment]
Then should an issue been open at clack?

**Comment by svetlyak40wt** [comment]
Probably yes, but first we need to check if a minimal clack app has the same problems when using "localhost" as an interface argument.

**Comment by not-null-nil** [comment]
Yes, I have done something like this:
```
(ql:quickload :clack)



(defvar *handler*
  (clack:clackup
      (lambda (env)
        (declare (ignore env))
        '(200 (:content-type "text/plain") ("Hello, Clack!")))
      :address "localhost"
      :server :wookie
      :port 5001))
```
and the error occur again.
I will open an issue at clack.

**Comment by not-null-nil** [comment]
Okay, since discussion has been moved to [here](https://github.com/fukamachi/clack/pull/166), I think this can be closed.
